app = "unavatar"
kill_signal = "SIGTERM"
kill_timeout = 5

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[http_service.concurrency]
  type = "requests"
  soft_limit = 2
  hard_limit = 4

[[restart]]
  policy = "on-failure"
  max_retries = 5

## some useful fly commands
# fly status # to see how many machines are running
# fly scale vm shared-cpu-2x --vm-memory=1024 # upgrade machines
